#!/usr/bin/php
<?php
namespace MCPI;

// Enable and show errors
ini_set('display_errors', 1);
ini_set('html_errors', 1);
error_reporting(E_ALL);

// Set environment to CLI for output, etc.
define('APP_ENVIRONMENT', 'CLI');

require_once __DIR__ . DIRECTORY_SEPARATOR . "code" . DIRECTORY_SEPARATOR . "autoload.php";

Core_Shell_Abstract::route($argv);

# vim: syntax=php
